version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: swen
      POSTGRES_PASSWORD: cremers
      POSTGRES_DB: jbrowse_config
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: scremers@limgroup.eu
      PGADMIN_DEFAULT_PASSWORD: Novobi14
    ports:
      - "5050:80"

  jbrowse2:
    build: ./jbrowse2  # This will use a Dockerfile inside a jbrowse2 directory
    container_name: jbrowse2_server
    ports:
      - "8080:80"
    volumes:
      - ./jbrowse2_data:/usr/share/nginx/html  # Mount the JBrowse data
      - ./config/config.json:/usr/share/nginx/html/config.json  # Mount your config.json inside the container
    restart: unless-stopped  # Ensure it restarts if it crashes

  flask_webform:
    build: ./flask_webform
    container_name: flask_webform_server
    ports:
      - "5000:5000"
    volumes:
      - ./flask_webform:/app
    restart: unless-stopped


volumes:
  postgres_data:
  jbrowse2_data:  # New volume for JBrowse2 data


